<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="STAR-PC" failures="2" tests="12" name="Test" time="27.81" errors="0" timestamp="2023-08-02T18:29:01 IST">
  <testcase classname="api.Testcases.TestuserDD" name="postusers" time="8.625"/>
  <testcase classname="api.Testcases.TestuserDD" name="postusers" time="1.198"/>
  <testcase classname="api.Testcases.TestuserDD" name="postusers" time="1.222"/>
  <testcase classname="api.Testcases.TestuserDD" name="Getusers" time="1.359">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.Testcases.TestuserDD.Getusers(TestuserDD.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Getusers -->
  <testcase classname="api.Testcases.TestuserDD" name="Getusers" time="1.165"/>
  <testcase classname="api.Testcases.TestuserDD" name="Getusers" time="1.222"/>
  <testcase classname="api.Testcases.TestuserDD" name="Putusers" time="1.232"/>
  <testcase classname="api.Testcases.TestuserDD" name="Putusers" time="1.202"/>
  <testcase classname="api.Testcases.TestuserDD" name="Putusers" time="1.213"/>
  <testcase classname="api.Testcases.TestuserDD" name="Deleteusers" time="1.16">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.Testcases.TestuserDD.Deleteusers(TestuserDD.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Deleteusers -->
  <testcase classname="api.Testcases.TestuserDD" name="Deleteusers" time="1.222"/>
  <testcase classname="api.Testcases.TestuserDD" name="Deleteusers" time="1.223"/>
</testsuite> <!-- Test -->
